### ISSUE TITLE
Question about CF worker to upload file as part of discord interaction response

### ISSUE THREAD

**Issue by gggrunt** [ssMMiles/discord-interactions#1]
I have been trying to figure out if it's possible to upload a file and use it as embed in a interaction/callback. I think CF worker fetch actually drops the filename parts header, I wonder if you have some thoughts or prior experience with this. Much appreciated.

**Comment by ssMMiles** [comment]
I've got an (apparently buggy) implementation of attachments in the `builders` package, and that seems to be working on CF workers at the moment:

```ts
async function main(ctx: SlashCommandContext) {
  await ctx.defer();
  const image = await fetch(imageUrl).then(res => res.blob());

  await ctx.edit(new MessageBuilder().addAttachments(
    { name: 'logo.png', data: image }
  ));
}
```

<img width="528" alt="image" src="https://user-images.githubusercontent.com/39016038/183711315-0b129ed2-a299-4c96-939a-c6f88302414e.png">

The code you probably want is in [`MessageBuilder.toFormData()`](https://github.com/ssMMiles/discord-interactions/blob/main/packages/builders/src/responses/MessageBuilder.ts), but looks like it's not quite right - I'll fix it when I get a moment and let you know.

**Comment by ssMMiles** [comment]
It was a really easy fix actually, and now all seems to work: https://github.com/ssMMiles/discord-interactions/commit/329b5e6f0bf2fcf2902444d4071a64fe0724cbdf

<img width="522" alt="image" src="https://user-images.githubusercontent.com/39016038/183720757-900646a6-4d2a-4574-ae21-882fdce33dd1.png">
