### ISSUE TITLE
core introduced use of 'process' to 0.3.20 - breaks cloudflare workers/wrangler.

### ISSUE THREAD

**Issue by tjsr** [ssMMiles/discord-interactions#5]
I've just rolled back version by version after updating a projects dependencies to latest - it looks like @discord-interactions/core introduced the use of `process.env.TOKEN_EXPIRY_OFFSET` in `app/contexts/Base`, so now when we try to use this in a cloudflare worker using wrangler it doesn't like that `process` is used.

I'll look at this a bit later to introduce some sort of patch.  It will probably just be a case of doing a null check on `process`.

https://github.com/ssMMiles/discord-interactions/blame/f50eef570f24406914bd06417df5f0e3ed849f64/packages/core/src/app/contexts/Base.ts#L21

v0.3.19 works, but v0.3.20 and v0.3.21 do not.

**Comment by ssMMiles** [comment]
Yeah that's a silly oversight on my end, should probably be testing for that.

Will push a fix in the next couple of hours.

**Comment by tjsr** [comment]
Oops - this has been sitting un-committed for a few days.
Thanks for looking at it quickly - you got to it before I could get home and look to fix it myself.

Unfortunately it doesn't seem to have resolved the issue - it merely referencing `process` which is undefined where ordinarily defined as a type externally seems to kill the process - I'm trying to find a solution.  Local development is a little difficult, but I've resolved that in the meantime.  I'll keep looking in to a resolution and if I find it, I'll submit a PR - would you like me to open another issue when I can provide better replication steps/details?

In the meantime I'm building off an `npm link`ed version with some slight modifications including this fix.  I'll have to either publish it in a private GH repo with a diff name as a fork if I want to compile my worker on CI with the updates or this fix.
